package com.sunil.recyclerviewviewpager.daogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunil.recyclerviewviewpager.daogen.DataWall;
import com.sunil.recyclerviewviewpager.daogen.WallTall;

import com.sunil.recyclerviewviewpager.daogen.DataWallDao;
import com.sunil.recyclerviewviewpager.daogen.WallTallDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataWallDaoConfig;
    private final DaoConfig wallTallDaoConfig;

    private final DataWallDao dataWallDao;
    private final WallTallDao wallTallDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataWallDaoConfig = daoConfigMap.get(DataWallDao.class).clone();
        dataWallDaoConfig.initIdentityScope(type);

        wallTallDaoConfig = daoConfigMap.get(WallTallDao.class).clone();
        wallTallDaoConfig.initIdentityScope(type);

        dataWallDao = new DataWallDao(dataWallDaoConfig, this);
        wallTallDao = new WallTallDao(wallTallDaoConfig, this);

        registerDao(DataWall.class, dataWallDao);
        registerDao(WallTall.class, wallTallDao);
    }
    
    public void clear() {
        dataWallDaoConfig.clearIdentityScope();
        wallTallDaoConfig.clearIdentityScope();
    }

    public DataWallDao getDataWallDao() {
        return dataWallDao;
    }

    public WallTallDao getWallTallDao() {
        return wallTallDao;
    }

}
