package com.sunil.recyclerviewviewpager.daogen;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WALL_TALL".
 */
@Entity
public class WallTall {

    @Id
    private Long id;
    private int name_id;

    @Generated(hash = 932310427)
    public WallTall() {
    }

    public WallTall(Long id) {
        this.id = id;
    }

    @Generated(hash = 1784982001)
    public WallTall(Long id, int name_id) {
        this.id = id;
        this.name_id = name_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getName_id() {
        return name_id;
    }

    public void setName_id(int name_id) {
        this.name_id = name_id;
    }

}
